### ISSUE TITLE
Error during sync

### ISSUE THREAD

**Issue by emreoktem** [jcoynel/app-store-reviews#7]
I get the following error while receiving reviews for Evernote

`TypeError: Cannot read property 'feed' of undefined
    at Request._callback (/user_code/node_modules/app-store-reviews/lib/app-store-reviews.js:29:20)
    at Request.self.callback (/user_code/node_modules/app-store-reviews/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/user_code/node_modules/app-store-reviews/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/user_code/node_modules/app-store-reviews/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)`

**Comment by jcoynel** [comment]
Hi @emreoktem,

Can you still reproduce this issue? Which version of app-store-reviews are you using? Is it Evernote for iOS or macOS? Any specific country?

Thanks

**Comment by emreoktem** [comment]
Hi @jcoynel , 

I've corrected the problem by modifying code but couldn't push it because not allowed.

Here's my modified version: https://gist.github.com/emreoktem/bd37fccba02901ce0a11636245025a9f

**Comment by jcoynel** [comment]
Hi @emreoktem,

You can submit a pull request (https://help.github.com/articles/about-pull-requests/).

I'll need to be able to reproduce the issue first, so it would help if you can answer the questions in my previous message.

Thanks
